import type { PrismaClient } from "@prisma/client";
import type { Message } from "discord.js";
import { describe, expect, it } from "vitest";
import {
  buildChannelRecentMessagesSummary,
  discordTools,
  type ChannelSummaryMessage,
} from "../src/tools/categories/discordTools";
import type { ToolExecutionContext, ToolResultEnvelope } from "../src/tools/ToolDefinition";
import { testLogger } from "./helpers";

describe("discordTools", () => {
  it("builds a deterministic recap with participants, highlights, topics, and a transcript", () => {
    const summary = buildChannelRecentMessagesSummary([
      makeSummaryMessage(
        "Alex",
        "Remember SubQ SubQ sparse attention for long-context tool tool calls.",
        "2026-06-19T12:01:00.000Z",
      ),
      makeSummaryMessage(
        "Blair",
        "The deploy is blocked by a voice smoke error; please fix it before the next run.",
        "2026-06-19T12:02:00.000Z",
      ),
      makeSummaryMessage("Casey", "Can someone confirm the tool-call eval passed?", "2026-06-19T12:03:00.000Z"),
    ]);

    expect(summary).toMatchObject({
      messageCount: 3,
      textMessageCount: 3,
      participants: ["Alex", "Blair", "Casey"],
      timeframe: {
        start: "2026-06-19T12:01:00.000Z",
        end: "2026-06-19T12:03:00.000Z",
      },
    });
    expect(summary.summary).toContain("Summarized 3 text messages from 3 participants");
    expect(summary.keyTopics).toContain("subq");
    expect(summary.highlights.map((highlight) => highlight.content).join(" ")).toContain("SubQ SubQ sparse attention");
    expect(summary.transcript).toContain("[Alex]: Remember SubQ SubQ sparse attention");
  });

  it("reports empty text content without fabricating a recap", () => {
    const summary = buildChannelRecentMessagesSummary([
      makeSummaryMessage("Alex", "   ", "2026-06-19T12:01:00.000Z"),
      makeSummaryMessage("Blair", null, "2026-06-19T12:02:00.000Z"),
    ]);

    expect(summary).toMatchObject({
      messageCount: 2,
      textMessageCount: 0,
      participants: [],
      highlights: [],
      transcript: "",
    });
    expect(summary.summary).toBe("Fetched 2 recent messages, but none contained text content to summarize.");
  });

  it("returns a deterministic channel recap from the summarize tool", async () => {
    const { tool, ctx } = makeSummaryContext({
      newestFirstMessages: [
        makeSummaryMessage("Casey", "Can someone confirm the tool-call eval passed?", "2026-06-19T12:03:00.000Z"),
        makeSummaryMessage(
          "Blair",
          "The deploy is blocked by a voice smoke error; please fix it before the next run.",
          "2026-06-19T12:02:00.000Z",
        ),
        makeSummaryMessage(
          "Alex",
          "Remember SubQ SubQ sparse attention for long-context tool tool calls.",
          "2026-06-19T12:01:00.000Z",
        ),
      ],
      expectedLimit: 5,
    });

    const result = await executeTool(tool, { limit: 5 }, ctx);

    expect(result).toMatchObject({
      ok: true,
      data: {
        channelId: "channel-1",
        messageCount: 3,
        textMessageCount: 3,
        participants: ["Alex", "Blair", "Casey"],
        summary: expect.stringContaining("Summarized 3 text messages"),
        note: "Deterministic recap generated by the tool; use the capped transcript only to verify details.",
      },
    });
    if (!result.ok) throw new Error(result.error);
    const data = result.data as Record<string, unknown>;
    expect(data.transcript).toMatch(/^\[Alex\]:/);
    expect(data.transcript).toContain("[Casey]: Can someone confirm");
    expect(data.keyTopics).toEqual(expect.arrayContaining(["subq", "tool"]));
  });

  it("adds Irene-observed activity metrics to guild stats when the database is available", async () => {
    const { tool, ctx } = makeStatsContext({
      db: {
        conversation: {
          count: async ({ where }: { where: unknown }) => {
            expect(where).toMatchObject({ guildId: "guild-1" });
            return 3;
          },
          findMany: async ({ where, take }: { where: unknown; take: number }) => {
            expect(where).toMatchObject({ guildId: "guild-1" });
            expect(take).toBe(5_000);
            return [
              { userId: "user-1", channelId: "channel-1", createdAt: new Date("2026-06-19T12:03:00.000Z") },
              { userId: "user-2", channelId: "channel-1", createdAt: new Date("2026-06-19T12:02:00.000Z") },
              { userId: "user-1", channelId: "channel-2", createdAt: new Date("2026-06-19T12:01:00.000Z") },
            ];
          },
        },
      } as unknown as PrismaClient,
    });

    const result = await executeTool(tool, {}, ctx);

    expect(result).toMatchObject({
      ok: true,
      data: {
        name: "Test Guild",
        members: 42,
        observedActivity: {
          available: true,
          source: "conversation_log",
          windowHours: 24,
          observedConversations: 3,
          observedConversationsPerDay: 3,
          activeUsers: 2,
          activeChannels: 2,
          sampledConversationRows: 3,
          lastObservedAt: "2026-06-19T12:03:00.000Z",
        },
      },
    });
  });

  it("reports guild activity as unavailable when persistence is disabled", async () => {
    const { tool, ctx } = makeStatsContext({ db: null });

    const result = await executeTool(tool, {}, ctx);

    expect(result).toMatchObject({
      ok: true,
      data: {
        observedActivity: {
          available: false,
          source: "conversation_log",
          reason: expect.stringContaining("database unavailable"),
        },
      },
    });
  });
});

function makeSummaryContext(options: {
  newestFirstMessages: ChannelSummaryMessage[];
  expectedLimit: number;
}): {
  tool: (typeof discordTools)[number];
  ctx: ToolExecutionContext;
} {
  const tool = discordTools.find((item) => item.name === "summarize_channel_recent_messages");
  if (!tool) throw new Error("summarize_channel_recent_messages tool missing");
  const messageCollection = new Map(options.newestFirstMessages.map((message, index) => [`message-${index}`, message]));

  return {
    tool,
    ctx: {
      guildId: "guild-1",
      channelId: "channel-1",
      userId: "user-1",
      memberPermissions: [],
      logger: testLogger,
      discordClient: {
        channels: {
          fetch: async (channelId: string) => {
            expect(channelId).toBe("channel-1");
            return {
              isTextBased: () => true,
              messages: {
                fetch: async (input: { limit: number }) => {
                  expect(input).toEqual({ limit: options.expectedLimit });
                  return messageCollection;
                },
              },
            };
          },
        },
      } as unknown as NonNullable<ToolExecutionContext["discordClient"]>,
    },
  };
}

function makeSummaryMessage(
  username: string,
  content: string | null,
  createdAt: string,
): ChannelSummaryMessage {
  return {
    content,
    createdAt: new Date(createdAt),
    author: { username },
  };
}

function makeStatsContext(options: { db: PrismaClient | null }): {
  tool: (typeof discordTools)[number];
  ctx: ToolExecutionContext;
} {
  const tool = discordTools.find((item) => item.name === "get_guild_stats");
  if (!tool) throw new Error("get_guild_stats tool missing");

  const guild = {
    id: "guild-1",
    name: "Test Guild",
    memberCount: 42,
    channels: { cache: { size: 7 } },
    roles: { cache: { size: 5 } },
    emojis: { cache: { size: 3 } },
    premiumSubscriptionCount: 2,
    createdAt: new Date("2020-01-01T00:00:00.000Z"),
  };

  return {
    tool,
    ctx: {
      guildId: "guild-1",
      channelId: "channel-1",
      userId: "user-1",
      memberPermissions: [],
      logger: testLogger,
      db: options.db,
      message: { guild } as unknown as Message,
    },
  };
}

async function executeTool(
  tool: (typeof discordTools)[number],
  args: unknown,
  ctx: ToolExecutionContext,
): Promise<ToolResultEnvelope> {
  const execute = tool.execute as (input: unknown, context: ToolExecutionContext) => Promise<ToolResultEnvelope>;
  return execute(args, ctx);
}
